version: 2
jobs:
  node:
    working_directory: ~/RNTest
    docker:
      - image: circleci/node:8
    steps:
      - checkout

      - run: npm install

      - save_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - node_modules


      - persist_to_workspace:
          root: ~/RNTest
          paths:
            - node_modules

  android:
    working_directory: ~/RNTest/android
    docker:
      - image: circleci/android:api-27-node8-alpha
    steps:
      - checkout:
          path: ~/RNTest

      - attach_workspace:
          at: ~/RNTest

      
      - run:
          name: Start Appium
          command: |
            node_modules/.bin/appium > /dev/null 2>&1

      - run:
          name: Run Appium Test 
          command: |
            node Appium.js      

  

workflows:
  version: 2
  node-android-ios:
    jobs:
      - node
      - android:
          requires:
            - node
      