version: 2
jobs:
  node:
    working_directory: ~/RNTest
    docker:
      - image: circleci/node:8
    steps:
      - checkout

      - run: npm install

      - save_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - node_modules

      - run:
          name: Appium tests
          command: |
            node Appium.js

      - persist_to_workspace:
          root: ~/RNTest
          paths:
            - node_modules

workflows:
  version: 2
  node-android-ios:
    jobs:
      - node
      